# Generated by Django 3.1.3 on 2021-05-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_type',
            field=models.CharField(blank=True, choices=[('DINE IN', 'DINE IN'), ('HOME DELIVERY', 'HOME DELIVERY')], max_length=100, null=True),
        ),
    ]
