# Generated by Django 3.1.3 on 2021-05-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210514_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG'), ('SNACKS', 'SNACKS')], max_length=200, null=True),
        ),
    ]
