# Generated by Django 3.1.3 on 2021-05-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
