# Generated by Django 3.1.3 on 2021-05-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210524_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_type',
            field=models.CharField(blank=True, choices=[('DINE IN', 'DINE IN'), ('HOME DELIVERY', 'HOME DELIVERY')], default='HOME DELIVERY', max_length=100, null=True),
        ),
    ]
