# Generated by Django 3.1.3 on 2021-05-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210525_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_type',
            field=models.CharField(blank=True, choices=[('HOME DELIVERY', 'HOME DELIVERY'), ('DINE IN', 'DINE IN')], max_length=100, null=True),
        ),
    ]
