# Generated by Django 3.1.3 on 2021-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210525_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=200, null=True),
        ),
    ]
